kacl:
  links:
    compare_versions_template: '{host}/tree/v{previous_version}...v{version}'
    unreleased_changes_template: '{host}/compare/v{latest_version}...HEAD'
    initial_version_template: '{host}/compare/v{version}'
