---
pull_request_rules:
  - name: Merge scala-steward's PRs - patch
    conditions:
      - author=scala-steward
      - status-success=microsite
      - status-success=format
      - status-success=compile and test 2.12.12
      - status-success=compile and test 2.13.3
      - body~=labels:.*semver-patch
    actions:
      merge:
        method: squash

  - name: Merge scala-steward's PRs - minor
    conditions:
      - author=scala-steward
      - status-success=microsite
      - status-success=format
      - status-success=compile and test 2.12.12
      - status-success=compile and test 2.13.3
      - body~=labels:*semver-minor
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: squash
