addSbtPlugin("org.scalameta"             % "sbt-scalafmt"               % "2.3.4")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"               % "0.1.11")
addSbtPlugin("com.geirsson"              % "sbt-ci-release"             % "1.5.3")
addSbtPlugin("io.chrisdavenport"         % "sbt-mima-version-check"     % "0.1.2")
addSbtPlugin("io.chrisdavenport"         % "sbt-no-publish"             % "0.1.0")
addSbtPlugin("org.scalameta"             % "sbt-mdoc"                   % "2.1.5")
addSbtPlugin("com.typesafe.sbt"          % "sbt-site"                   % "1.4.0")
addSbtPlugin("io.github.jonas"           % "sbt-paradox-material-theme" % "0.6.0")
